import {
  FiGrid,
  FiShoppingBag,
  FiBox,
  FiTag,
  FiPackage,
  FiUsers,
  FiTruck,
  FiShoppingCart,
  FiDollarSign,
  FiBriefcase,
  FiUserCheck,
  FiBarChart2,
  FiSettings,
  FiMapPin,
  FiUser,
  FiClock,
  FiCheckSquare,
  FiCreditCard,
  FiAward,
  FiMonitor,
  FiLayers,
  FiCpu,
  FiCheckCircle,
  FiHome,
  FiFileText,
  FiShield,
  FiCoffee,
  FiTv,
  FiCalendar,
  FiPieChart,
  FiTrash2,
  FiTrendingUp,
  FiHeart,
  FiActivity,
} from "react-icons/fi";

export const INDUSTRY_CODES = {
  RETAIL: "RETAIL",
  GYM: "GYM",
  TEXTILE: "TEXTILE",
  RESTAURANT: "RESTAURANT",
  LAUNDRY: "LAUNDRY",
  MEDICAL_SHOP: "MEDICAL_SHOP",
};

export const ROUTE_MODULE_MAP = {
  // Core & Dashboards
  "/dashboard": "DASHBOARD",
  "/dashboard/sales-dashboard": "DASHBOARD",
  "/dashboard/inventory-dashboard": "DASHBOARD",
  "/dashboard/finance-dashboard": "DASHBOARD",
  "/dashboard/pos-dashboard": "DASHBOARD",
  "/dashboard/hrm-dashboard": "DASHBOARD",

  // POS Terminal
  "/pos": "SALES",
  "/pos/cart": "SALES",
  "/pos/checkout": "SALES",
  "/pos/receipt": "SALES",

  // Retail Products & Inventory
  "/admin/products": "PRODUCTS",
  "/admin/products/view": "PRODUCTS",
  "/admin/products/add": "PRODUCTS",
  "/admin/products/edit": "PRODUCTS",
  "/admin/products/details": "PRODUCTS",
  "/admin/categories": "CATEGORIES",
  "/admin/brand": "BRANDS",
  "/admin/units": "PRODUCTS",
  "/warehouse/stock": "INVENTORY",
  "/warehouse": "INVENTORY",
  "/warehouse/add": "INVENTORY",
  "/warehouse/transfer": "INVENTORY",
  "/admin/inventory": "INVENTORY",

  // Retail Sales & Customers
  "/customers": "CUSTOMERS",
  "/customers/add": "CUSTOMERS",
  "/customers/edit": "CUSTOMERS",
  "/customers/view": "CUSTOMERS",
  "/sales": "SALES",
  "/sales/add": "SALES",
  "/sales/edit": "SALES",
  "/invoices": "SALES",
  "/invoices/create": "SALES",

  // Retail Purchases & Suppliers
  "/admin/suppliers": "SUPPLIERS",
  "/purchases": "PURCHASES",
  "/purchases/add": "PURCHASES",
  "/purchases/edit": "PURCHASES",

  // Gym Modules
  "/gym/members": "MEMBERS",
  "/gym/plans": "MEMBERSHIP_PLANS",
  "/gym/membership-plans": "MEMBERSHIP_PLANS",
  "/gym/trainers": "TRAINERS",
  "/gym/attendance": "ATTENDANCE",
  "/gym/payments": "PAYMENTS",
  "/gym/branches": "BRANCHES",

  // Textile Modules
  "/textile/products": "PRODUCTS",
  "/textile/products/add": "PRODUCTS",
  "/textile/raw-materials": "RAW_MATERIALS",
  "/textile/production": "PRODUCTION",
  "/textile/quality-control": "QUALITY_CONTROL",

  // Restaurant Modules
  "/restaurant/dashboard": "RESTAURANT",
  "/restaurant/tables": "RESTAURANT",
  "/restaurant/reservations": "RESTAURANT",
  "/restaurant/menu": "RESTAURANT",
  "/restaurant/pos": "RESTAURANT",
  "/restaurant/kitchen": "RESTAURANT",
  "/restaurant/orders": "RESTAURANT",
  "/restaurant/wastage": "RESTAURANT",
  "/restaurant/food-cost": "RESTAURANT",

  // Laundry Modules
  "/laundry/dashboard": "LAUNDRY",
  "/laundry/pos": "LAUNDRY",
  "/laundry/orders": "LAUNDRY",
  "/laundry/services": "LAUNDRY",
  "/laundry/garments": "LAUNDRY",
  "/laundry/processing": "LAUNDRY",
  "/laundry/ready": "LAUNDRY",
  "/laundry/pickup": "LAUNDRY",
  "/laundry/delivery": "LAUNDRY",
  "/laundry/reports": "LAUNDRY",

  // Medical Shop / Pharmacy Modules
  "/medical/dashboard": "MEDICAL_SHOP",
  "/medical/pos": "MEDICAL_SHOP",
  "/medical/medicines": "MEDICAL_SHOP",
  "/medical/categories": "MEDICAL_SHOP",
  "/medical/batches": "MEDICAL_SHOP",
  "/medical/expiry": "MEDICAL_SHOP",
  "/medical/prescriptions": "MEDICAL_SHOP",
  "/medical/purchases": "MEDICAL_SHOP",
  "/medical/inventory": "MEDICAL_SHOP",
  "/medical/returns": "MEDICAL_SHOP",
  "/medical/reports": "MEDICAL_SHOP",

  // Core Operations
  "/admin/expenses": "EXPENSES",
  "/admin/branches": "BRANCHES",
  "/admin/employees": "EMPLOYEES",
  "/admin/employees/add": "EMPLOYEES",
  "/admin/employees/view": "EMPLOYEES",
  "/admin/departments": "EMPLOYEES",
  "/reports": "REPORTS",
  "/reports/inventory": "REPORTS",
  "/reports/purchase": "REPORTS",
  "/reports/sales": "REPORTS",
  "/admin/settings": "SETTINGS",
  "/settings": "SETTINGS",
  "/settings/profile": "SETTINGS",
};

export const MASTER_NAVIGATION_CATALOG = [
  // Shared Core & Dashboards
  { moduleCode: "DASHBOARD", label: "Dashboard", href: "/dashboard", icon: FiGrid },

  // Gym Industry Modules
  { moduleCode: "MEMBERS", label: "Gym Members", href: "/gym/members", icon: FiUsers, industry: "GYM" },
  { moduleCode: "MEMBERSHIP_PLANS", label: "Membership Plans", href: "/gym/plans", icon: FiAward, industry: "GYM" },
  { moduleCode: "TRAINERS", label: "Gym Trainers", href: "/gym/trainers", icon: FiUserCheck, industry: "GYM" },
  { moduleCode: "ATTENDANCE", label: "Attendance Log", href: "/gym/attendance", icon: FiCheckSquare, industry: "GYM" },
  { moduleCode: "PAYMENTS", label: "Payments & Fees", href: "/gym/payments", icon: FiCreditCard, industry: "GYM" },
  { moduleCode: "BRANCHES", label: "Gym Fitness Centers & Branches", href: "/gym/branches", icon: FiMapPin, industry: "GYM" },
  { moduleCode: "SUPPLIERS", label: "Equipment Suppliers", href: "/admin/suppliers", icon: FiTruck, industry: "GYM" },

  // Textile Industry Modules
  { moduleCode: "PRODUCTS", label: "Textile Products", href: "/textile/products", icon: FiShoppingBag, industry: "TEXTILE" },
  { moduleCode: "RAW_MATERIALS", label: "Raw Materials", href: "/textile/raw-materials", icon: FiLayers, industry: "TEXTILE" },
  { moduleCode: "PRODUCTION", label: "Production Tracking", href: "/textile/production", icon: FiCpu, industry: "TEXTILE" },
  { moduleCode: "INVENTORY", label: "Inventory Stock", href: "/warehouse/stock", icon: FiPackage, industry: "TEXTILE" },
  { moduleCode: "WAREHOUSES", label: "Mill Warehouses", href: "/warehouse", icon: FiHome, industry: "TEXTILE" },
  { moduleCode: "QUALITY_CONTROL", label: "Quality Control", href: "/textile/quality-control", icon: FiCheckCircle, industry: "TEXTILE" },
  { moduleCode: "BRANCHES", label: "Mills & Manufacturing Units", href: "/admin/branches", icon: FiMapPin, industry: "TEXTILE" },
  { moduleCode: "SUPPLIERS", label: "Yarn & Dye Suppliers", href: "/admin/suppliers", icon: FiTruck, industry: "TEXTILE" },
  { moduleCode: "SALES", label: "Fabric Sales & Export", href: "/sales", icon: FiShoppingCart, industry: "TEXTILE" },

  // Retail Industry Modules
  { moduleCode: "SALES", label: "POS Terminal", href: "/pos", icon: FiMonitor, industry: "RETAIL" },
  { moduleCode: "SALES", label: "Barcode Printing", href: "/admin/pos/barcode-print", icon: FiTag, industry: "RETAIL" },
  { moduleCode: "PRODUCTS", label: "Products", href: "/admin/products/view", icon: FiShoppingBag, industry: "RETAIL" },
  { moduleCode: "CATEGORIES", label: "Categories", href: "/admin/categories", icon: FiBox, industry: "RETAIL" },
  { moduleCode: "BRANDS", label: "Brands", href: "/admin/brand", icon: FiTag, industry: "RETAIL" },
  { moduleCode: "PRODUCTS", label: "Units of Measure", href: "/admin/units", icon: FiBox, industry: "RETAIL" },
  { moduleCode: "INVENTORY", label: "Warehouse Management", href: "/warehouse", icon: FiBriefcase, industry: "RETAIL" },
  { moduleCode: "CUSTOMERS", label: "Customers", href: "/customers", icon: FiUsers, industry: "RETAIL, MEDICAL_SHOP" },
  { moduleCode: "SUPPLIERS", label: "Goods Vendors & Suppliers", href: "/admin/suppliers", icon: FiTruck, industry: "RETAIL, MEDICAL_SHOP" },
  { moduleCode: "PURCHASES", label: "Purchases", href: "/purchases", icon: FiShoppingCart, industry: "RETAIL" },
  { moduleCode: "SALES", label: "Sales Orders", href: "/sales", icon: FiShoppingCart, industry: "RETAIL" },
  { moduleCode: "SALES", label: "Invoices", href: "/invoices", icon: FiFileText, industry: "RETAIL" },
  { moduleCode: "BRANCHES", label: "Store Outlets & Branches", href: "/admin/branches", icon: FiMapPin, industry: "RETAIL, MEDICAL_SHOP" },,

  // Restaurant Industry Modules
  { moduleCode: "RESTAURANT", label: "Dashboard", href: "/restaurant/dashboard", icon: FiGrid, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Restaurant Outlets Setup", href: "/restaurant/manage", icon: FiMapPin, industry: "RESTAURANT", adminOnly: true },
  { moduleCode: "RESTAURANT", label: "Restaurant POS", href: "/restaurant/pos", icon: FiMonitor, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Floor & Tables", href: "/restaurant/tables", icon: FiCoffee, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Reservations", href: "/restaurant/reservations", icon: FiCalendar, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Menu & Recipes", href: "/restaurant/menu", icon: FiBox, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Raw Materials / Ingredients", href: "/admin/products/view", icon: FiPackage, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Food Purchases", href: "/purchases", icon: FiShoppingCart, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Suppliers", href: "/admin/suppliers", icon: FiTruck, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Staff Management", href: "/admin/employees/view", icon: FiUserCheck, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Orders", href: "/restaurant/orders", icon: FiShoppingCart, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Wastage Management", href: "/restaurant/wastage", icon: FiTrash2, industry: "RESTAURANT" },
  { moduleCode: "RESTAURANT", label: "Analytics & Reports", href: "/reports", icon: FiBarChart2, industry: "RESTAURANT" },

  // Laundry Industry Modules
  { moduleCode: "LAUNDRY", label: "Laundry Dashboard", href: "/laundry/dashboard", icon: FiGrid, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Laundry POS", href: "/laundry/pos", icon: FiMonitor, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Active Orders", href: "/laundry/orders", icon: FiShoppingCart, industry: "LAUNDRY" },
  { moduleCode: "BRANCHES", label: "Laundry Outlets & Branches", href: "/admin/branches", icon: FiMapPin, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Services & Categories", href: "/laundry/services", icon: FiBox, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Garment Tracking", href: "/laundry/garments", icon: FiTag, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Processing Queue", href: "/laundry/processing", icon: FiClock, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Ready Orders", href: "/laundry/ready", icon: FiCheckCircle, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Pickup / Deliveries", href: "/laundry/delivery", icon: FiTruck, industry: "LAUNDRY" },
  { moduleCode: "LAUNDRY", label: "Laundry Reports", href: "/laundry/reports", icon: FiBarChart2, industry: "LAUNDRY" },

  // Medical Shop Industry Modules
  { moduleCode: "MEDICAL_SHOP", label: "Pharmacy Dashboard", href: "/medical/dashboard", icon: FiGrid, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Pharmacy POS", href: "/medical/pos", icon: FiMonitor, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Medicines List", href: "/medical/medicines", icon: FiActivity, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Medicine Categories", href: "/medical/categories", icon: FiBox, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Medicine Batches", href: "/medical/batches", icon: FiLayers, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Expiry Management", href: "/medical/expiry", icon: FiClock, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Prescriptions Log", href: "/medical/prescriptions", icon: FiFileText, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Medicine Purchases", href: "/medical/purchases", icon: FiShoppingCart, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Pharmacy Inventory", href: "/medical/inventory", icon: FiPackage, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Returned Medicines", href: "/medical/returns", icon: FiTrash2, industry: "MEDICAL_SHOP" },
  { moduleCode: "MEDICAL_SHOP", label: "Pharmacy Reports", href: "/medical/reports", icon: FiBarChart2, industry: "MEDICAL_SHOP" },

  // Shared Core Operations
  { moduleCode: "EMPLOYEES", label: "Employees / Staff", href: "/admin/employees/view", icon: FiUserCheck },
  { moduleCode: "REPORTS", label: "Reports & Analytics", href: "/reports", icon: FiBarChart2 },
];
