const landingSchema = {
  LandingPage: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      logoText: { type: "string" },
      logoHighlight: { type: "string" },
      loginText: { type: "string" },
      heroTag: { type: "string" },
      heroTitle: { type: "string" },
      heroDescription: { type: "string" },
      heroImage: { type: "string", nullable: true },
      heroBackgroundImage: { type: "string", nullable: true },
      heroButtonText: { type: "string" },
      dashboardTitle: { type: "string" },
      dashboardSubtitle: { type: "string" },
      aboutTag: { type: "string" },
      aboutTitle: { type: "string" },
      aboutDescription: { type: "string" },
      aboutImage1: { type: "string", nullable: true },
      aboutImage2: { type: "string", nullable: true },
      aboutImage3: { type: "string", nullable: true },
      aboutImage4: { type: "string", nullable: true },
      footerText: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  UpdateLandingPage: {
    type: "object",
    properties: {
      logoText: { type: "string" },
      logoHighlight: { type: "string" },
      loginText: { type: "string" },
      heroTag: { type: "string" },
      heroTitle: { type: "string" },
      heroDescription: { type: "string" },
      heroButtonText: { type: "string" },
      dashboardTitle: { type: "string" },
      dashboardSubtitle: { type: "string" },
      aboutTag: { type: "string" },
      aboutTitle: { type: "string" },
      aboutDescription: { type: "string" },
      footerText: { type: "string" },
    },
  },
};

export default landingSchema;
